{% set name = "segment-lidar" %}
{% set version = "0.1.7" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 10f4991d93dbd7a3a4d7f2fcc83faf5ae8203349655ddac0098c71acc59216db

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python >=3.9
  run:
    - folium
    - ipyleaflet
    - pyshp
    - python >=3.9

test:
  imports:
    - segment_lidar

about:
  home: "https://github.com/Yarroudh/segment-lidar"
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: "Python package for segmenting aerial LiDAR data using Segment-Anything Model (SAM) from Meta AI."
  doc_url: https://yarroudh.gitbook.io/segment-lidar
  dev_url: https://github.com/Yarroudh/segment-lidar

extra:
  recipe-maintainers:
    - yarroudh